services:
  clientservice:
    container_name: clientservice 
    build:
      context: .
    image: dreamagici4n/client-service
    volumes:
      - .:/app
    tty: true
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/client_service
    ports:
      - 3000:3000
      - 5000:5000

  postgres:
    image: postgres:12.19-alpine3.19
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=client_service
    volumes:
      - ./src/main/resources/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080