services:
  clientservice:
    container_name: clientservice 
    build:
      context: .
    image: dreamagici4n/client-service
    volumes:
      - .:/app
    tty: true
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - ${CLIENT_SERVICE_PORT}:${CLIENT_SERVICE_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}

  postgres:
    image: postgres:12.19-alpine3.19
    env_file:
      - ./.env
    volumes:
      - ./src/main/resources/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}