image: alpine:latest

stages:
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

before_script:
  - apk add --no-cache docker
  - apk add --no-cache docker-compose
  - apk add --no-cache git

test:
  stage: test
  script:
    - docker-compose up --build -d
    - docker exec clientservice mvn test
    - docker-compose down --volumes
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - filename=$(find ./target -name 'clientservice-*.jar' | head -n 1)
    - version=$(basename "$filename" | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
    - CONTAINER_IMAGE_TAG="$CI_REGISTRY_IMAGE:$version"
    - echo -e "FROM maven:3.9.6-eclipse-temurin-22-alpine\nWORKDIR /app\nCOPY $filename /app\nCMD [\"sh\", \"-c\", \"java -jar $(basename "$filename")\"]" > DockerfileProd
    - docker build -f DockerfileProd -t $CONTAINER_IMAGE_TAG .
    - docker push $CONTAINER_IMAGE_TAG
  only:
    - main