image: alpine:latest

stages:
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

before_script:
  - apk add --no-cache docker
  - apk add --no-cache docker-compose

test:
  stage: test
  script:
    - docker-compose up --build -d
    - docker run dreamagici4n/client-service mvn test
    - docker-compose down --volumes
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo $CONTAINER_IMAGE_TAG
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo "$CI_DEPLOY_PASSWORD"
    - echo -e "FROM maven:3.9.6-eclipse-temurin-22-alpine\nWORKDIR /app\nCOPY ./target/clientservice-0.0.1-SNAPSHOT.jar /app\nCMD [\"sh\", \"-c\", \"java -jar clientservice-0.0.1-SNAPSHOT.jar\"]" > DockerfileProd
    - docker build -f DockerfileProd -t $CONTAINER_IMAGE_TAG .
    - docker push $CONTAINER_IMAGE_TAG
  only:
    - main