image: alpine:latest

stages:
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/

before_script:
  - apk add --no-cache docker

test:
  stage: test
  script:
    - docker build -t test-container .
    - docker run test-container mvn test
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - echo "FROM maven:3.9.6-eclipse-temurin-22-alpine
            WORKDIR /app
            COPY ./target/clientservice-0.0.1-SNAPSHOT.jar /app
            CMD [ "sh", "-c","java -jar clientservice-0.0.1-SNAPSHOT.jar"]" > Dockerfile
    - docker build -f Dockerfile -t dreamagici4n/client-service .
    - docker push dreamagici4n/client-service
  only:
    - main